apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: 855221455178.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest
        ports:
        - containerPort: 80
